name: TypescriptCheck

on: pull_request

jobs:
  ts_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: yarn install --immutable --immutable-cache --check-cache
      - name: TS test
        run: yarn ts
